### ISSUE TITLE
Do we want to clear NULL values?

### ISSUE THREAD

**Issue by peterjaap** [magento-hackathon/EAVCleaner#12]
```
Start Cleaning Eav Values
We fix your Database 10320 Rows :-) Done!
Clean up 0 rows in catalog_product_entity_varchar
Clean up 48633 rows in catalog_product_entity_int
Clean up 6741 rows in catalog_product_entity_decimal
Clean up 3246 rows in catalog_product_entity_text
Clean up 447 rows in catalog_product_entity_datetime
Deleting NULL value 0
Deleting NULL value 0
Deleting NULL value 0
Deleting NULL value 0
Deleting NULL value 0
Deleting NULL value 0
Deleting NULL value 0
Deleting NULL value 0
Deleting NULL value 0
Deleting NULL value 0
Deleting NULL value 0
Deleting NULL value 0
Deleting NULL value 0
Deleting NULL value 0
Deleting NULL value 0
Deleting NULL value 0
Deleting NULL value 0
Deleting NULL value 0
Deleting NULL value 0
Deleting NULL value 0
Deleting NULL value 0
Deleting NULL value 0
Deleting NULL value 0
Deleting NULL value 0
... etc
```

Is this something we want? Couldn't we just skip deleting the NULL values?

**Comment by peterjaap** [comment]
Yes we do.

**Comment by Amex68** [comment]
quick question:

Where are the NULL values from?
Do i delete it by doing the following? 

DELETE FROM catalog_category_entity_datetime WHERE `value` IS NULL;
DELETE FROM catalog_category_entity_decimal WHERE `value` IS NULL;
DELETE FROM catalog_category_entity_int WHERE `value` IS NULL;
DELETE FROM catalog_category_entity_text WHERE `value` IS NULL;
DELETE FROM catalog_category_entity_varchar WHERE `value` IS NULL;

DELETE FROM catalog_product_entity_datetime WHERE `value` IS NULL;
DELETE FROM catalog_product_entity_decimal WHERE `value` IS NULL;
DELETE FROM catalog_product_entity_gallery WHERE `value` IS NULL;
DELETE FROM catalog_product_entity_group_price WHERE `value` IS NULL;
DELETE FROM catalog_product_entity_int WHERE `value` IS NULL;
DELETE FROM catalog_product_entity_media_gallery WHERE `value` IS NULL;
DELETE FROM catalog_product_entity_media_gallery_value WHERE `label` IS NULL;
DELETE FROM catalog_product_entity_text WHERE `value` IS NULL;
DELETE FROM catalog_product_entity_tier_price WHERE `value` IS NULL;
DELETE FROM catalog_product_entity_varchar WHERE `value` IS NULL;

Cheers :)
