### ISSUE TITLE
Syntax Error in CleanUpAttributesAndValuesWithoutParentCommand.php

### ISSUE THREAD

**Issue by syhe** [magento-hackathon/EAVCleaner#14]
#10 introduced a syntax error at [CleanUpAttributesAndValuesWithoutParentCommand.php:68](https://github.com/magento-hackathon/EAVCleaner/pull/10/files#diff-28ea55e73f88767c9b2e4b506b717b64R68).

```
Parse error: syntax error, unexpected '.' in /usr/local/share/n98-magerun/modules/hackathon_EAVCleaner/src/FIREGENTO/Magento/Command/Eav/CleanUpAttributesAndValuesWithoutParentCommand.php on line 68
```

**Comment by jhoelzl** [comment]
I made a pull request for this: #15
