### ISSUE TITLE
Working on M2 V2.1.7

### ISSUE THREAD

**Issue by andidhouse** [magento-hackathon/EAVCleaner#25]
Wondering if this works on Magento 2.1.7.
We copied the files to the app/code/EAVCleaner folder but magento does not show the module.

Thanks!

**Comment by daim2k5** [comment]
Did you choose the right brunch as mentioned in our readme?

**Comment by andidhouse** [comment]
@daim2k5 thanks for your answer.

Yes we choose the right one. We also put the composer.json file into app/code/EAVCleaner.

Wondering maybe magento has changed the structure as all other extension have a company folder:

app/code/extensioncompany/extensionname

**Comment by maartenv1** [comment]
Please can you tell me how to install. Not with but how. I dont know what command line i must use to install in with composer.

**Comment by UrbanSurfers** [comment]
@andidhouse @daim2k5 same here with Magento 2.1.9, have to copy in `app/code/**Hackaton**/EAVCleaner` folder to see the module with the `magento module:status` (look at the **registration.php** file).
I can now enable it and execute commands. 

But even if I delete products before / after installing the module, the `magento eav:media:remove-unused` command always return : (`--dry-run` also)
```
+----------+
| filepath |
+----------+
Found 0.00 MB unused images in 0 files
```

Could you provide us the command for installing the module with composer to solve this issue ?
like `composer require .....................`

Thanks for your help

**Comment by sprankhub** [comment]
Closing as 2.1 is EOL.
