### ISSUE TITLE
Working on M2.2.1 RC ?

### ISSUE THREAD

**Issue by angelflo** [magento-hackathon/EAVCleaner#26]
Hello,
Please can you tell me if your extension work with last Magento RC version 2.2.1 ? 
thanks a lot to share your work with us.

**Comment by IanFiretoys** [comment]
I got this working on 2.2.2 by adding it to app\code\Hackaton\EAVCleaner and running the following from magento install folder
php bin/magento module:enable Hackaton_EAVCleaner
php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento cache:flush
php bin/magento setup:static-content:deploy -f

the eav: commands should now work

**Comment by Tjitse-E** [comment]
It seems that this repo is abandoned. So i've forked the repo and enabled composer installation for Magento 2.2 and 2.3: https://github.com/Vendic/EAVCleaner

**Comment by sprankhub** [comment]
Closing as 2.2 is EOL.
