### ISSUE TITLE
Working op magento 2.2.5?

### ISSUE THREAD

**Issue by ghost** [magento-hackathon/EAVCleaner#27]
Is this module working still on Working op magento 2.2.5 open source?

Is the development ended on this module or will it be updated in the future?

Best regards

**Comment by peterjaap** [comment]
I haven't tried it on 2.2.5. Let us know if it works.

I doubt anyone is actively working on this. The original authors in any case aren't.

**Comment by ghost** [comment]
Best,
I have no testing environment at the moment so i can not test.
I was using Wamp and Xampp but this is far from perfect.

I have to build a testing environment on a Virtual machine but i need to take some more online lessons to understand this. I want a exact copy of my environment, the goal is to achieve a synchronization of all files to the virtual machine so everything is the same. If this is possible (which i think it is) and up and running i can test this extension.

**Comment by peterjaap** [comment]
@koopjesboom little tip; take a look at https://github.com/byteinternet/hypernode-docker

**Comment by ghost** [comment]
Best,
Thank you very much i will go look into this.
Have a good weekend, best regards KBM
