### ISSUE TITLE
eav:media:remove-unused: Do Not Remove Custom Placeholder Images

### ISSUE THREAD

**Issue by sprankhub** [magento-hackathon/EAVCleaner#29]
If I see correctly, custom placeholder images defined in one of these settings

- `catalog/placeholder/image_placeholder`
- `catalog/placeholder/menu_image_placeholder`
- `catalog/placeholder/small_image_placeholder`
- `catalog/placeholder/thumbnail_placeholder`

are stored in the directory `/media/catalog/product/placeholder/default`. The command `eav:media:remove-unused` removes these images. I think images in this directory should be skipped and should not be removed. They are not referenced in the database, but are still used.

**Comment by tmotyl** [comment]
solved with https://github.com/magento-hackathon/EAVCleaner/pull/36
