### ISSUE TITLE
Dont understand what this does

### ISSUE THREAD

**Issue by seansan** [magento-hackathon/EAVCleaner#35]
Dont understand what this does

Is it possible from someon knowledgeable to elaborate a little more or provide an example in the readme

eav:config:restore-use-default-value Check if config admin value and storeview value are the same, so "use default" doesn't work anymore. Delete the storeview values.

eav:attributes:restore-use-default-value Check if product attribute admin value and storeview value are the same, so "use default" doesn't work anymore. Delete the storeview values.

**Comment by tmotyl** [comment]
hi @seansan 
attr and config values can be defined on default and store view level.
These commands are removing store view value if it's the same as default one (thus making "use default" checkbox being selected).
