### ISSUE TITLE
How do I uninstall this extension?

### ISSUE THREAD

**Issue by poliver1** [magento-hackathon/EAVCleaner#37]
Hiya. I'm struggling to uninstall this extension.

I've removed the folder fromm app/code
I've removed the entry from setup_module table
I've removed entry from config.php

but still whenever i run setup:upgrade i get this

PHP Fatal error:  Uncaught Error: Class 'Hackathon\EAVCleaner\Console\Command\RestoreUseDefaultValueCommand' not found in /httpdocs/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:116

I've searched the whole database and can't find anymore Hackathon entries, pls help

**Comment by sprankhub** [comment]
You probably need to clean the `generated/code` directory as well and run a DI compile.

**Comment by poliver1** [comment]
Thank you for your time.

I've cleared the generated/code directory and ran a DI compile but got another error. :(

```
There are no commands defined in the "app:config" namespace.

Did you mean one of these?
    setup:config
    setup:store-config

In ClassReader.php line 19:

  Class Hackathon\EAVCleaner\Console\Command\RestoreUseDefaultValueCommand do
  es not exist
```

I guess I'll have to search FTP for entries.

**Comment by sprankhub** [comment]
It seems obvious, but you also flushed the cache, right? ;-)
