### ISSUE TITLE
Not found table helper in Magento 2.3.1

### ISSUE THREAD

**Issue by YachYaroslav** [magento-hackathon/EAVCleaner#39]
```$this->getHelper('table')``` throws the LogicException about not found helper near 87 line in EAVCleaner/Console/Command/RemoveUnusedMediaCommand.php.

Possible solution to change the next code:

```php
$this->getHelper('table')
            ->setHeaders($headers)
            ->setRows($table)->render($output);
```

with

```php
(new \Symfony\Component\Console\Helper\Table($output))
		    ->setHeaders($headers)
            ->setRows($table)->render();
```

**Comment by sprankhub** [comment]
Closing as the problematic code is not used any more.
