### ISSUE TITLE
What is the Purpose of this extension?

### ISSUE THREAD

**Issue by Eddcapone** [magento-hackathon/EAVCleaner#43]
There is information missing about the purpose of this extension.

**Comment by daim2k5** [comment]
@Eddcapone 
"Purpose of this project is to check for different flaws that can occur due to EAV and provide cleanup functions." See Readme

**Comment by Eddcapone** [comment]
This is very vague. Can you give any details about these "flaws". At least one example where we can see the benefit of your extension?

**Comment by daim2k5** [comment]
@Eddcapone I'm not sure if you are a trolling.
If you look closer under the headline "Commands" in the Readme we describe the flaws.

**Comment by Eddcapone** [comment]
Your description is really bad and missing a informative introduction, instead we have to study the commands and the code to see what the extension is doing. I think you are trolling us here.

**Comment by daim2k5** [comment]
@Eddcapone sorry for the bad description and missing a informative introduction. You are open to improve the points that you mentioned (we are an open source project)

**Comment by Eddcapone** [comment]
@daim2k5 , How am I supposed to do this if I am not a contributor of the project and don't know anything about it? It should be done by the autors

**Comment by mageconsult** [comment]
@Eddcapone 

Maybe also the about text will help: "Clean up your Magento database by removing orphaned, unused and wrongly added attribute, attribute values and settings."

This is an open source project, which some developers had developed in one single day on a hackathon in Utrecht in their spare time just for fun. Over the years it evolved to what you see today. There is some description in the readme, so you should be able to use it. Each command describes the benefits.

If you have improvements, you are welcome. Fork it, change it, make a pull request. And that quick you are a contributor.

**Comment by Eddcapone** [comment]
@mageconsult , I don't know anything about the extension and I don't use it because of this, so I am the wrong person to write a description for it.

**Comment by daim2k5** [comment]
@Eddcapone Thanks for your input.
