### ISSUE TITLE
Using crontabs for periodic cleanup of unused media

### ISSUE THREAD

**Issue by dtoonen-maxserv** [magento-hackathon/EAVCleaner#44]
Hi, absolute beginner here. I've been messing around with the EAVCleaner and testing its functionality, so far I've found that the module is a nice fit for what we intend to use the module for. I have a question, however (pardon me if this isn't the right place to ask).

I've been looking to run certain commands to periodically clean up unused media, so specifically: I'd like to run the `bin/magento eav:media:remove-unused` on a weekly basis so a sprawl of unused media doesn't spiral out of control. 

I've tried adding the command to the crontab but so far I've been stumped and not getting it to work locally. I was curious if such a functionality has been created before (specifically for the EAVCleaner) and/or if somebody is able to point me in the right direction.

**Comment by sprankhub** [comment]
Welcome :) Absolutely right to ask here!

If you can run the command on that machine manually, you can also let it run via crontab. One thing to watch out for is that you need to be in the right directory to run it, so something like:

    cd /path/to/your/shop/root && bin/magento eav:media:remove-unused

If it does not work for you, try redirecting the output from crontab to a file and see what the error is:

    cd /path/to/your/shop/root && bin/magento eav:media:remove-unused > /path/to/log.txt

I stumbled upon your sentence "getting it to work locally". Usually, locally, no cron service is set up at all, so the cronjob is not run automatically. Maybe that is the issue? Simply try another action, where you know that it works (creating a file or whatever) and see if it works via crontab.

Hope this helps.
