### ISSUE TITLE
Maybe create method clean_all?

### ISSUE THREAD

**Issue by seansan** [magento-hackathon/EAVCleaner#6]
Maybe create method clean_all?

Something safe to run that does what it says

**Comment by peterjaap** [comment]
Not sure we would want this. Some things are really specific and can even destroy a functional database. All these commands should be used with caution and always on a test database first. Having a method to run ALL commands goes against that.

Besides that, I've just added the --dry-run option everywhere. If that is missing, we need user input to verify they really want this. Adding this option would involve skipping that process, which isn't something we want.
